######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 10 13:23:23 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .


QT+=network
# Input
HEADERS += client.h login.h server.h ui.h want.h join.h
SOURCES += client.cpp login.cpp main.cpp server.cpp ui.cpp want.cpp join.cpp
RESOURCES += res.qrc

